// <auto-generated />
namespace MICRO.WMS.WEB.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class mac11241830 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mac11241830));
        
        string IMigrationMetadata.Id
        {
            get { return "201811241031019_mac11241830"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
